apiVersion: v1
kind: Namespace
metadata:
  name: cert-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-https-config
  namespace: cert-test
data:
  default.conf: |
    server {
        listen 443 ssl;
        server_name test.lab.hortonew.com;
        
        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: cert-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: tls-cert
          mountPath: /etc/nginx/ssl
          readOnly: true
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: tls-cert
        secret:
          secretName: nginx-test-tls
      - name: nginx-config
        configMap:
          name: nginx-https-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: cert-test
spec:
  type: LoadBalancer
  selector:
    app: nginx-test
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-test-cert
  namespace: cert-test
spec:
  secretName: nginx-test-tls
  issuerRef:
    name: letsencrypt-staging # Use staging first to test!
    kind: ClusterIssuer
  dnsNames:
  - test.lab.hortonew.com
