---
# Example ExternalSecret that syncs from Vault
# This will create a Kubernetes Secret named "demo-credentials" in the external-secrets namespace
# by pulling data from Vault's secret/demo/credentials path
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-credentials
  namespace: external-secrets
spec:
  # Refresh interval - how often to sync from Vault
  refreshInterval: 1m

  # Reference to the ClusterSecretStore
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  # The target Kubernetes Secret to create/update
  target:
    name: demo-credentials
    creationPolicy: Owner

  # Data to pull from Vault
  data:
  # Pull individual fields from Vault secret
  - secretKey: username
    remoteRef:
      key: demo/credentials
      property: username

  - secretKey: password
    remoteRef:
      key: demo/credentials
      property: password

  - secretKey: api-key
    remoteRef:
      key: demo/credentials
      property: api-key
---
# Example: Pull entire secret from Vault (all key-value pairs)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-credentials-all
  namespace: external-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: demo-credentials-all
    creationPolicy: Owner
  # dataFrom pulls the entire secret
  dataFrom:
  - extract:
      key: demo/credentials
---
# Example: Template the secret data
# This allows you to transform the secret data before creating the Kubernetes Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-credentials-templated
  namespace: external-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: demo-credentials-templated
    creationPolicy: Owner
    # Template to create custom secret format (e.g., for config files)
    template:
      engineVersion: v2
      data:
        # Create a database connection string
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@postgres.example.com:5432/mydb"
        # Create a config.json file
        config.json: |
          {
            "username": "{{ .username }}",
            "api_key": "{{ index . "api-key" }}"
          }
  data:
  - secretKey: username
    remoteRef:
      key: demo/credentials
      property: username
  - secretKey: password
    remoteRef:
      key: demo/credentials
      property: password
  - secretKey: api-key
    remoteRef:
      key: demo/credentials
      property: api-key
