---
# Example: Using namespace-scoped SecretStore
# This demonstrates using a SecretStore (instead of ClusterSecretStore)
# which is scoped to a specific namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-credentials-namespace-store
  namespace: external-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend-ns-external-secrets
    kind: SecretStore
  target:
    name: demo-credentials-namespace-store
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: demo/credentials
      property: username
  - secretKey: password
    remoteRef:
      key: demo/credentials
      property: password
