apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 1.0.0
    chart: external-secrets
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
        # Use cert-manager for webhook certificates
        webhook:
          port: 9443
          certManager:
            enabled: true
            cert:
              duration: 8760h  # 1 year
              renewBefore: 720h  # 30 days
              issuerRef:
                kind: ClusterIssuer
                name: selfsigned-issuer
        # Disable built-in cert-controller since we're using cert-manager
        certController:
          create: false
        # Resources for the operator
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-setup
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://github.com/hortonew/monitoring-lab-k8s/
    path: apps/external-secrets/k8s/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
